{
 "title": "Network",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orbi_system_uptime_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component Uptimes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orbi_uptime_seconds_total", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "Transmitted Bytes / Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "orbi_transmitted_bytes_per_second",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Received Bytes / Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 5 },
   "targets": [
    { "expr": "orbi_received_bytes_per_second", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "Transmitted Packets Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(orbi_transmitted_packets_total[1m])",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Received Packets Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "rate(orbi_received_packets_total[1m])",
     "legendFormat": "{{component}}"
    }
   ]
  }
 ]
}