name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - name: Build
        run: make

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: orbi-exporter-linux-amd64
          path: |
            build/orbi-exporter-linux-amd64
