name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Build
        run: make
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: orbi-exporter-linux-amd64
          path: |
            build/orbi-exporter-linux-amd64

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          outputs: type=tar,dest=build/orbi-exporter-linux-amd64-${{github.sha}}.tar.gz
          push: false
      - name: Upload container image
        uses: actions/upload-artifact@v4
        with:
          name: orbi-exporter-linux-amd64-${{github.sha}}.tar.gz
          path: |
            build/orbi-exporter-linux-amd64-${{github.sha}}.tar.gz
  container-image:
    needs: build
    if: ${{ github.ref_name == 'main' && github.repository == 'LukeWinikates/orbi-exporter' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: download binary
        uses: actions/download-artifact@v4
        with:
          name: orbi-exporter-linux-amd64
          path: build/orbi-exporter-linux-amd64
      - name: build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lukewinikates/orbi-exporter:${{ github.sha }}
            lukewinikates/orbi-exporter:latest