name: container-image
on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [container-image-build]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: download binary
        uses: actions/download-artifact@v4
        with:
          name: orbi-exporter-linux-amd64
          path: build/orbi-exporter-linux-amd64
      - name: build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lukewinikates/orbi-exporter:${{ github.sha }}
            lukewinikates/orbi-exporter:latest
